### ISSUE TITLE
Comments are not working

### ISSUE THREAD

**Issue by spookybear0** [RealistikDash/GDPyS#55]

**Comment by RealistikDash** [comment]
Beginning investigation now.
# Current Info.
- Occurs when loding comments
- Some users aren't able to be fetched from userID, leading to the `Failed searching for user 11. Should be skipped.` message.
- It is caused by the line `comment_user = await user_helper.get_object(await user_helper.accid_userid(comment.user_id))` in the levelextras handler. This line causes an `AssertionError`.
